services:
  embeddingapp:
    image: embedding-app-image:latest
    ports:
      - "8051:8501"
    volumes:
      - ./data:/usr/src/app/data
      - ./openai_db:/usr/src/app/openai_db
      - ./alternative_db:/usr/src/app/alternative_db