FROM python-base:latest

WORKDIR /user/src/app

COPY init.py ./
COPY const.py ./
COPY embedding_app.py ./
COPY .env ./
COPY ./data ./data

EXPOSE 8501

ENTRYPOINT ["streamlit", "run", "embedding_app.py", "--server.port=8501", "--server.address=0.0.0.0"]