services:
  customchatbot:
    image: custom_chatbot:latest
    ports:
      - "8501:8501"
      - "8080:8502"
    user: "0:0" 
    volumes:
      - ./model:/user/src/app/model
      - ./openai_db:/user/src/app/openai_db
      - ./alternative_db:/user/src/app/alternative_db
  nginx:
    image: mysslconfig:latest
    volumes:
      - ~/conf/nginxconf/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ~/conf/nginxconf/certs:/etc/nginx/ssl:ro
    ports:
      - "443:443"
    depends_on:
      - customchatbot