FROM python-base:latest

WORKDIR /user/src/app

COPY init.py ./
COPY website_url_extractor.py ./
COPY embedding_manager.py ./
COPY const.py ./
COPY embedding_backend.py ./
COPY .env ./
COPY ./data ./data

EXPOSE 5000
# Set environment variables
ENV FLASK_ENV=development

# Command to run the Flask application
CMD ["python", "embedding_backend.py"]