FROM python-base:latest

WORKDIR /user/src/app

COPY const.py ./
COPY .env ./
COPY chat_app.py ./
COPY website_url_extractor.py ./
COPY embedding_manager.py ./
COPY init.py ./

EXPOSE 8501

ENTRYPOINT ["streamlit", "run", "chat_app.py", "--server.port=8501", "--server.address=0.0.0.0"]